language: node_js
node_js:
- node
install:
  - npm install -g firebase-tools
script:
  - npm run lint
after_success:
  - npm run deploy
notifications:
  email: false
branches:
  only:
    - master
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN    